AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function deployment template

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-api
      CodeUri: ./
      Handler: index.handler
      Runtime: Node.js 20.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          "
      Events: {}
      